name: project_2
description: A modern stock tracking app with Firebase and Finnhub API.

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  http: ^1.2.2
  provider: ^6.0.5
  fluttertoast: ^8.2.1
  google_fonts: ^4.0.4
  lottie: ^2.3.2
  url_launcher: ^6.1.7
  fl_chart: ^0.55.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

# Uncomment and customize fonts if needed
# fonts:
#   - family: Lato
#     fonts:
#       - asset: assets/fonts/Lato-Regular.ttf
#       - asset: assets/fonts/Lato-Bold.ttf

dependency_overrides:
  fl_chart:
    git:
      url: https://github.com/imaNNeo/fl_chart.git
      ref: main




