// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZXvVpzlDj8VqKzKXx9MCAXEP22WlEnfs',
    appId: '1:59333879888:web:1cddd8400c86aabeb4c955',
    messagingSenderId: '59333879888',
    projectId: 'project2-420c6',
    authDomain: 'project2-420c6.firebaseapp.com',
    storageBucket: 'project2-420c6.firebasestorage.app',
    measurementId: 'G-VSCK6L5Z9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6TzDxAYMxGTR0hjZE2PmoF8DhSjLWDUU',
    appId: '1:59333879888:android:5bf225ab7642c756b4c955',
    messagingSenderId: '59333879888',
    projectId: 'project2-420c6',
    storageBucket: 'project2-420c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuvDdGVzHfNZti3pxmkcpJnx2vwRd6Eo0',
    appId: '1:59333879888:ios:b9dd945a017889d2b4c955',
    messagingSenderId: '59333879888',
    projectId: 'project2-420c6',
    storageBucket: 'project2-420c6.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuvDdGVzHfNZti3pxmkcpJnx2vwRd6Eo0',
    appId: '1:59333879888:ios:b9dd945a017889d2b4c955',
    messagingSenderId: '59333879888',
    projectId: 'project2-420c6',
    storageBucket: 'project2-420c6.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZXvVpzlDj8VqKzKXx9MCAXEP22WlEnfs',
    appId: '1:59333879888:web:f3133e929eabb5dcb4c955',
    messagingSenderId: '59333879888',
    projectId: 'project2-420c6',
    authDomain: 'project2-420c6.firebaseapp.com',
    storageBucket: 'project2-420c6.firebasestorage.app',
    measurementId: 'G-ZMXGC0YJ3H',
  );
}
